# Server Configuration
server.port=9000

# Spring Configuration
spring.application.name=SafetyNetAlerts

# Logging Configuration (for Log4j)
logging.level.root=INFO
logging.level.com.openclassrooms=DEBUG
logging.file.path=logs/safetynetalerts.log

# Jackson Configuration (for JSON processing)
spring.jackson.serialization.INDENT_OUTPUT=true

